  // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLKIPwlXgK1-o4j6gsg4hzMjYy-TU0sKc',
    appId: '1:201631963713:web:52e351a226d4b90c1104c0',
    messagingSenderId: '201631963713',
    projectId: 'income-and-expense-track-1e04c',
    authDomain: 'income-and-expense-track-1e04c.firebaseapp.com',
    storageBucket: 'income-and-expense-track-1e04c.firebasestorage.app',
    measurementId: 'G-S597Y84R61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhvR0E4AH_dMB1gAnllC78gUAjmBlfb3c',
    appId: '1:201631963713:android:26ccab1965dd0fe81104c0',
    messagingSenderId: '201631963713',
    projectId: 'income-and-expense-track-1e04c',
    storageBucket: 'income-and-expense-track-1e04c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkZ209WcJdQWgon0ko6ZP3WWHrjthaUn0',
    appId: '1:201631963713:ios:4068411668adb7b01104c0',
    messagingSenderId: '201631963713',
    projectId: 'income-and-expense-track-1e04c',
    storageBucket: 'income-and-expense-track-1e04c.firebasestorage.app',
    iosBundleId: 'com.example.incomeAndExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkZ209WcJdQWgon0ko6ZP3WWHrjthaUn0',
    appId: '1:201631963713:ios:4068411668adb7b01104c0',
    messagingSenderId: '201631963713',
    projectId: 'income-and-expense-track-1e04c',
    storageBucket: 'income-and-expense-track-1e04c.firebasestorage.app',
    iosBundleId: 'com.example.incomeAndExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLKIPwlXgK1-o4j6gsg4hzMjYy-TU0sKc',
    appId: '1:201631963713:web:6854d1b0b026bc6a1104c0',
    messagingSenderId: '201631963713',
    projectId: 'income-and-expense-track-1e04c',
    authDomain: 'income-and-expense-track-1e04c.firebaseapp.com',
    storageBucket: 'income-and-expense-track-1e04c.firebasestorage.app',
    measurementId: 'G-L38S9L8XBT',
  );
}
